name: Build and Run djvu2mask

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:latest

    steps:
      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Checko
