name: Clean, Build, and Run with Make on Debian

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: apt-get update && apt-get install -y build-essential libjpeg-dev libtiff-dev

      - name: Clean the build directory
        run: make clean

      - name: Build with make
        run: make VERBOSE=1

      - name: List files in tools directory (debug)
        run: ls -l tools/

      - name: List files in root directory (debug)
        run: ls -l

      - name: Run the program with repository file
        run: ./tools/djvu2mask test/Hochfeder-02_PT01_020bis.djvu test/Hochfeder-02_PT01_020bis_output.png
