name: Debug Build and Run djvu2mask

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Checkout
        run: |
          echo "Checking after checkout"
          echo "Current directory: $(pwd)"
          ls -la

      - name: Ensure correct working directory
        run: |
          cd $GITHUB_WORKSPACE
          echo "After changing to GITHUB_WORKSPACE: $(pwd)"
          ls -la
          if [ -d .git ]; then
            echo "In Git repository: $(pwd)"
          else
            echo "Not in a Git repository"
            exit 1
          fi
