name: Build and Run djvu2mask

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential libjpeg-dev libtiff-dev autotools-dev autoconf automake libtool git

      - name: Set safe Git directory
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Verify and Change Directory to Git Repository
        run: |
          cd $GITHUB_WORKSPACE
          if [ -d .git ]; then
            echo "In Git repository: $(pwd)"
          else
            echo "Not in a Git repository"
            exit 1
          fi

      - name: Clean untracked files
        if: always()
        run: |
          git clean -fdx
          git reset --hard

      - name: Clean en
